### PR TITLE
Wrap NSLog's in `#if DEBUG`

### PR DESCRIPTION
**Pull request by hsoi**
Wrap NSLog's in `#if DEBUG / #endif` so they don't clutter up, slow down, and risk exposing potentially sensitive information into the logs.

### CODE REVIEW

**Comment by erylee** [comment]
@hsoi, Thanks.

**Comment by hsoi** [comment]
@erylee You're welcome :-)

**Comment by fabiosoft** [comment]
how can i enable/disable this DEBUG flag?

**Comment by alexyu1989** [comment]
@fabiosoft mqtt.logLevel = .off

**Comment by fabiosoft** [comment]
Unfortunately that doesn't work... 
`Value of type CocoaMQTT has no member 'logLevel'`


mqtt.logLevel = .off

**Comment by alexyu1989** [comment]
@fabiosoft make sure the version >= 1.0.13

**Comment by fabiosoft** [comment]
oh amazing! I was using cocoapod version, not the git one.

Thanks

**Comment by alexyu1989** [comment]
@fabiosoft 
1.0.16 is already released on cocoapods. Use pod update.

**Pull request merged**
