### PR TITLE
mqtt is made disconnect properly (or so it seems)

### PR DESCRIPTION
**Pull request by nauyihs**
This solves the issue of mqtt keeps disconnecting and connecting again.

I have a problem here when disconnect mqtt and reconnect immediately, say within 2 seconds, it then keeps disconnecting and reconnecting. I am not completely sure what is the cause of it but this for now solves my problem.

### CODE REVIEW

**Comment by alexyu1989** [comment]
I have tested it and did not find the problem. 
And I thought we need to find a clear reason to modify the code.

**Comment by nauyihs** [comment]
Oh sorry, here is my case: We have an app when user logs in (via their google account), we connect mqtt, when they log out, we disconnect it. The problem occurs when the user logs out and immediately logs back in, mqtt connects and after about 30 secs disconnects - this pattern repeats indefinitely. As I see no problem in our code here, I am suspecting there may be a little glitch in your source code, so I made a little change on how mqtt disconnects and it actually worked, although I may have missed the real problem as my understanding of mqtt is limited.

**Comment by alexyu1989** [comment]
@nauyihs Thanks. Which version do you use? Does the version has autoReconnect feature? (Cocoamqtt.autoReconnect: Bool)

**Comment by nauyihs** [comment]
I am using 1.0.14, no auto reconnect. I haven't tried the latest version yet but I have gone through the changes and I don't think autoReconnect would have any effect on the problem I am experiencing..

**Comment by alexyu1989** [comment]
@orbitbot Thanks a lot. I should follow Since GCDAsyncSocket's suggest usage.

@nauyihs Seems like your pr is a direct way to fix the bug. And it also should set delegate to self before socket.connect(). Plz wait for the next pod version in an hour.

**Pull request merged**
